---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: docker
    commands:
      - docker build -t dntskdev/extdns:${DRONE_COMMIT_BRANCH} .
      - docker push dntskdev/extdns:${DRONE_COMMIT_BRANCH}
      - docker tag dntskdev/extdns:${DRONE_COMMIT_BRANCH} dntskdev/extdns:latest
      - docker push dntskdev/extdns:latest
    volumes:
      - name: cache
        path: /root/.cache/pip
      - name: docker_sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker
    when:
      event: push
  - name: tag
    image: docker
    commands:
      - "docker build -t dntskdev/extdns:${DRONE_TAG} ."
      - "docker push dntskdev/extdns:${DRONE_TAG}"
    volumes:
      - name: cache
        path: /root/.cache/pip
      - name: docker_sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker
    when:
      event: tag
volumes:
  - name: cache
    host:
      path: /opt/docker/drone/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker

trigger:
  branch:
    - master

---
kind: pipeline
type: docker
name: build_site

steps:
  - name: build
    image: docker
    commands:
      - docker build -f Dockerfile_site -t dntskdev/extdns_site:${DRONE_COMMIT_BRANCH} .
      - docker push dntskdev/extdns_site:${DRONE_COMMIT_BRANCH}
      - docker tag dntskdev/extdns_site:${DRONE_COMMIT_BRANCH} dntskdev/extdns_site:latest
      - docker push dntskdev/extdns_site:latest
    volumes:
      - name: cache
        path: /root/.cache/pip
      - name: docker_sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker
volumes:
  - name: cache
    host:
      path: /opt/docker/drone/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker

trigger:
  branch:
    - master

---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /opt
        - docker-compose pull extdns extdns_site
        - docker-compose up -d extdns extdns_site
  - name: deploy_site
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /opt
        - docker-compose pull extdns_site
        - docker-compose up -d extdns_site

depends_on:
  - build
  - build_site

trigger:
  branch:
    - master
