version: '3.0'

services:
  extdns:
    image: dntskdev/extdns:latest
    container_name: "extdns"
    restart: always
    environment:
      - CF_TOKEN=YourCloudFlareToken
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    labels:
      - "extdns.cf.nginx.hostname=example.com"
